# Macro file for example B1
# 
# To be run preferably in batch, without graphics:
# % exampleB1 run2.mac
#
#/run/numberOfWorkers 4
/run/initialize
#
/control/verbose 2
/run/verbose 2
#
# optical photon 6 MeV to the direction (0.,0.,1.)
# 10000 events
#
/gun/particle opticalphoton
/gun/energy 3 eV
#
/run/printProgress 100
/run/beamOn 100
# 
# proton 210 MeV to the direction (0.,0.,1.)
# 1000 events
#
#/gun/particle proton
#/gun/energy 210 MeV
##
#/run/beamOn 1000
